version: "3.7"

services:
  # web server
  nginx:
    image: nginx:latest
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      # app
      - ./app/www:/www/
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      # logs
      - ./log/nginx:/var/log/nginx

  # php-fpm
  php-fpm:
    build: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./app/www:/www/
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      # logs
      - ./log/php-fpm:/var/log/php-fpm

  # database
  mysql:
    image: mysql:5.7
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-your_mysql_password}

  pma:
    image: phpmyadmin/phpmyadmin
    env_file: 
      - .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-100M}
